POST http://localhost:3002/api/survey
content-type: application/json
Authorization:  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyaWFud2FjaGlyYSIsImlkIjoiNjE3MTZmOGExOWY2ZmQwZTcxYzY3MzExIiwiaWF0IjoxNjM0ODMzNzA3fQ.3Utuus-GC56OQK0CoxcQK08PE7qG78Xxf5QJ2i8wk1g

{
    "admin":"61716f8a19f6fd0e71c67311",
    "title": "Another  Survey",
    "questions": [
        {
            "passage": "What do you dislike?",
            "options":[
                {
                    "choice": "A",
                    "value": "Waking up early"
                },
                {
                    "choice": "B",
                    "value": "Sleeping late"
                }
            ]
        },
        {
            "passage": "Squares or circles?",
            "options":[
                {
                    "choice": "A",
                    "value": "square"
                },
                {
                    "choice": "B",
                    "value": "circles"
                }
            ]
        },
        {
            "passage": "Black or white?",
            "options":[
                {
                    "choice": "A",
                    "value": "Black"
                },
                {
                    "choice": "B",
                    "value": "White"
                }
            ]
        },
        {
            "passage": "BMW or Mercedes?",
            "options":[
                {
                    "choice": "A",
                    "value": "BMW"
                },
                {
                    "choice": "B",
                    "value": "Mercedes"
                }
            ]
        }
    ]

}